#!/bin/bash

bspc config border_width 1
bspc config window_gap 2

# Setting up desktops
i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d {1,2,3,4,5,6,7,8,9,0}
    let i++
done
NMON=$i
unset i

bspc config top_padding 16

# Visual options
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true
# Spring loco
#bspc config normal_border_color "#332d29"
#bspc config active_border_color "#1B3A40"
#bspc config focused_border_color "#1B3A40"
#bspc config presel_feedback_color "#9e6ffe"
bspc config normal_border_color "#453e3f"
bspc config active_border_color "#607271"
bspc config focused_border_color "#607271"
bspc config presel_feedback_color "#8c8369"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Pointer
bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_modifier mod1


# Rules
bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Skype state=pseudo_tiled
bspc rule -a shutter state=floating
bspc rule -a conky sticky=off manage=off
bspc rule -a feh state=floating
bspc rule -a '*:XMathematic' follow=off state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs:emacs state=tiled
bspc rule -a libreoffice-calc state=tiled
bspc rule -a Wine:TeamViewer.exe state=floating

sleep 2

/home/edeustua/.config/bspwm/panel/panel &
